docs: workflow examples
w3c-ccg/traceability-interop pull request #106
Opened 2022-03-01 10:03 UTC by nissimsan

2022-03-01 16:30 UTC, TallTed requested changes

2022-03-01 16:30 UTC, TallTed commented on docs/index.html
> +          to indicate that presentations relates to the same type of workflow. In the above example two separate 7501 Entry
```suggestion
          to indicate that presentations relate to the same type of workflow. In the above example, two separate 7501 Entry
```

2022-03-01 16:30 UTC, TallTed commented on docs/index.html
> +          workflow definition it clear to CBP that both relate to the same types of import workflows.
```suggestion
          workflow definition, it is made clear to CBP that both relate to the same types of import workflows.
```

2022-03-01 16:30 UTC, TallTed commented on docs/index.html
> +          Workflows <em>instances</em> indicates that individual presentations are part of the very same workflow. The majority
```suggestion
          Workflow <em>instances</em> indicate that separate individual presentations are part of the very same workflow. The majority
```

2022-03-01 16:30 UTC, TallTed commented on docs/index.html
> +          of data elements of a "10+2" Importer Security Filing must be presented to CBP no later than 24h before vessel
```suggestion
          of data elements in a "10+2" Importer Security Filing must be presented to CBP no later than 24 hours before vessel
```

2022-03-01 16:30 UTC, TallTed commented on docs/index.html
> +          loading, the remaining data elements no later than 24h before arrival. Specifying the same workflow instance indicates
```suggestion
          loading, and the remaining data elements no later than 24 hours before arrival. Specifying the same workflow instance indicates 
```

2022-03-01 18:14 UTC, mkhraisha commented
I was under the impression that the resolution to #85 was to move vocabulary similar to this to trace vocab?

2022-03-07 18:46 UTC, mkhraisha approved these changes
Disregard my previous comment, this was discussed on the call, happy as is.

2022-03-07 19:55 UTC, OR13 approved these changes

2022-03-08 18:39 UTC, mprorock approved these changes

2022-03-08 18:39 UTC, merged