feat: workflow instance join readme
w3c-ccg/traceability-interop pull request #170
Opened 2022-04-07 11:58 UTC by nissimsan

Added README. Not so much a tutorial as a business-oriented scenario.

2022-04-07 17:05 UTC, TallTed requested changes

2022-04-07 17:05 UTC, TallTed commented on docs/tutorials/workflow-join/README.md
> +Receiving the Commercial Invoice (10), Customs can also join the two graphs, thus knowing that the original Proforma Invoice relates to the Freight Forwarder’s presentations.
```suggestion
_Customs_ verifies the House BL from the _Freight Forwarder_ (6). 
Receiving the Commercial Invoice (10), _Customs_ can also join the two graphs, thus knowing that the original Proforma Invoice relates to the _Freight Forwarder_’s presentations. 
```

2022-04-12 16:17 UTC, mkhraisha approved these changes

2022-04-12 18:15 UTC, OR13 approved these changes

2022-04-12 18:15 UTC, merged