Remove Merkle Proof Selective Disclosure
w3c-ccg/traceability-interop pull request #235
Opened 2022-05-19 17:39 UTC by OR13

There are no standard implementations.

2022-05-20 06:54 UTC, nissimsan approved these changes

2022-05-20 16:13 UTC, mkhraisha requested changes
+1 to removing both, can you edit this PR to remove the BBS+ section that is just above it too?

2022-05-24 17:58 UTC, mprorock reviewed
This is a developer note that makes clear that in theory this is something that "could" be done, but you shouldn't.  I am ok with leaving it in, but will not object to removing the section on merkle proofs

2022-05-24 18:00 UTC, mkhraisha approved these changes

2022-05-24 18:02 UTC, merged