feat: removing todo plus service in singular
w3c-ccg/traceability-interop pull request #239
Opened 2022-05-24 09:50 UTC by nissimsan

Removing the todo of https://github.com/w3c-ccg/traceability-vocab/pull/412. Merge the trace-vocab PR first.

2022-05-24 18:02 UTC, mprorock approved these changes

2022-05-24 18:07 UTC, OR13 requested changes
Provide a DID Document example.

2022-05-25 11:09 UTC, nissimsan commented
I've updated the DID Document example with the necessary context, pointing at the new term we just defined.

```json
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/traceability/v1"
  ],
```

With this `TraceabilityAPI` gets the proper term: 
`<did:web:platform.example:organization:123#traceability-api> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/traceability#TraceabilityAPI> .`

And yes, https://w3id.org/traceability#TraceabilityAPI resolves beautifully to reveal what it is we are doing here.

2022-05-25 12:50 UTC, OR13 approved these changes

2022-05-25 13:13 UTC, BenjaminMoe approved these changes

2022-05-31 17:42 UTC, merged