Optional security for public credentials
w3c-ccg/traceability-interop pull request #296
Opened 2022-07-14 20:59 UTC by nissimsan

I'm fairly sure this is the right syntax for optional security. The swagger editor accepts it too:

![image](https://user-images.githubusercontent.com/34443212/179085121-2d017b2d-ca66-4b0c-b7ba-4cd0cb1639ae.png)

2022-07-15 10:58 UTC, mprorock requested changes
Security is not optional on a GET for credentials

2022-07-15 14:11 UTC, TallTed commented
Does "public credentials" roughly equate to "public key"?

If so, then yes, it should be possible to make it available _with or without_ authn/authz layers, i.e., _security on public key_ (which I would use to encrypt something destined for decryption with the fully secure private key) _should be optional._ The owner of that public key should be able to protect it *or not.*

2022-07-15 16:55 UTC, OR13 commented on docs/openapi/resources/credential.yml
> +    - {}
IMO its a MUST.

2022-07-15 16:56 UTC, OR13 requested changes
No optional security for get credentials.

2022-07-15 18:17 UTC, TallTed commented
> [@OR13] No optional security for get credentials.

Why must I authenticate and/or be explicitly authorized to GET a PUBLIC KEY?

Or by "no optional security", do you mean "it MUST be possible to require authn and/or authz of GETters, which may include authn as ANYONE a/k/a BLANK a/k/a ANONYMOUS _a la_ anonymous FTP (or HTTP! retrieval"?

2022-07-15 20:04 UTC, mprorock commented
> > [@OR13] No optional security for get credentials.
> 
> Why must I authenticate and/or be explicitly authorized to GET a PUBLIC KEY?
> 
> Or by "no optional security", do you mean "it MUST be possible to require authn and/or authz of GETters, which may include authn as ANYONE a/k/a BLANK a/k/a ANONYMOUS _a la_ anonymous FTP (or HTTP!) retrieval"?

https://w3c-ccg.github.io/traceability-interop/#authorization

For one very good reason - this Specification (and accompanying API) is driven around supply chain and specifically cross border trade - there are hard requirements around authZ, audit capabilities, and access to data on a need to no basis, no matter how innocuous that data may seem.  

There are other standards in development, or that already exist, e.g. various did methods that deal with how do i get a public key that someone wants to expose publicly

credentials by nature have more than a key in them, they have claims and other info that may be identifiable or correlatable, and this specification desires to ensure that all data is protected.  I state this as one of the original authors of this work item to reflect the needs of my customers.

if your implementation (which i have not seen in the test suite) does not wish to support a strict level of authZ on all resources, this probably isn't the right spec to be working on

2022-07-15 20:05 UTC, mprorock commented on docs/openapi/resources/credential.yml
> +    - {}
we have a hard customer requirement on MUST and I will object to anything other than a MUST here

2022-07-15 20:33 UTC, TallTed commented
So, a workflow that is 99.9% identical to the "supply chain" use case but does not involve cross-border trade (say, because it only involves domestic trade) will require a 100% distinct specification?

Note that I'm not saying that authn and authz MUST NOT be used, only that these are not required in 100% of deployments or usage scenarios, and that therefore it SHOULD (I think MUST) be possible for the administrator and/or other keepers of business logic to set *this* credential (or server or service) behind an authn/authz wall and *that* credential (or server or service) behind no GET/READ protection whatsoever.

2022-07-15 21:18 UTC, OR13 commented on docs/openapi/resources/credential.yml
> +    - {}
```suggestion
```

2022-07-15 21:19 UTC, OR13 commented
This repo is about supply chain interoperability tests, we add requirements based on consensus.

We also have to cover all decisions we make here with tests.

This PR is about "get public credentials".... which could return 100% of the credentials on the api origin.

I don't feel there is any reason why such an endpoint should be allowed to be unsecured by a "conformant implementation" of this specification.

There are plenty of "public credential registry use cases"... but this repo isn't about that.

Transmute does support "public get credential by id" use cases... for specific credentials... in fact, everyone who passes the current tests has to, if you support revocation lists...

But let's not talk about all the issues on this PR, let's focus on the change set, and use issues and discussions to handle other topics.

I have suggested the change I would like to see to the PR, 
and I'm not planning on approving any PRs that allow for `GET /credentials` without an authorization header.

2022-07-18 09:30 UTC, nissimsan commented on docs/openapi/resources/credential.yml
> +    - {}
@mkhraisha, this isn't `getCredentials`, it's `getCredentialById`.

2022-07-18 12:22 UTC, BenjaminMoe commented
>  and I'm not planning on approving any PRs that allow for GET /credentials without an authorization header.

It's not. This is a PR for defining access to a *single* credential via `/credentials/{credential-id}`.  In other words not allowing optional security on this pull request would *break revocation lists*.

2022-07-18 13:03 UTC, OR13 commented on docs/openapi/resources/credential.yml
> +    - {}
ahh, this is wrong... revocation lists require this to be open to any verifier...

2022-07-18 13:03 UTC, OR13 commented on docs/openapi/resources/credential.yml
> +    - {}
I need to read more carefully.

2022-07-18 13:03 UTC, OR13 commented on docs/openapi/resources/credential.yml
> +    - {}
we will all fail interop tests with verifiers if they cannot resolve revocation list credentials.

2022-07-18 13:03 UTC, OR13 approved these changes

2022-07-18 13:05 UTC, OR13 commented
I am dumb, i just realized that... tests for revocation lists would be failing if we broke this... any verifier needs to resolve the revocation list, and that call cannot require authentication.

2022-07-19 18:04 UTC, merged