chore: require type property for credentialStatus
w3c-ccg/traceability-interop pull request #396
Opened 2022-09-08 17:17 UTC by brownoxford

This PR makes the `credentialStatus.type` property required (when `credentialStatus` is present) in the `options` object when posting to `/credentials/issue`.

This change is driven by the vc-api specification as outlined in #395 

Fixes #395

2022-09-09 15:06 UTC, brownoxford commented
> Noting that this will be a big breaking change for us at least

I'd love to hear more about this one. Note that this is NOT making `credentialStatus` a required element, only that when `credentialStatus` is present, it MUST contain a `type` property. Previously, you could submit with an empty object for `credentialStatus`.

Are you saying that your current implementation omits `type`, or am I misunderstanding?

2022-09-12 11:42 UTC, nissimsan approved these changes

2022-09-13 15:43 UTC, brownoxford commented
@nissimsan @BenjaminMoe @OR13 Can you help me understand how this is a breaking change for you? That was unexpected, and I want to make sure I am not missing something here.

2022-09-13 17:54 UTC, OR13 requested changes
I've like to see an explicit call out to all the apis related to this, and make sure we are ready to take this change, and we have updated everything consistently.

2022-09-13 17:54 UTC, nissimsan commented
@brownoxford , we need to review the VC-API, compare and agree on a common shape between interop and VC-API. Will you action this, pls?

2022-09-13 17:55 UTC, OR13 commented
Provide links to the following:

- VCAPI Credential Issue
- VCAPI Credential Status Update

- Trace Credential Issue
- Trace Credential Status Update

The schemas MUST all agree.

The types, enums, etc... should be consistent.

2022-09-16 20:55 UTC, mkhraisha commented
Below are all the links, reformatting for legibility:

> * VCAPI Credential Issue

https://github.com/w3c-ccg/vc-api/blob/d275b08a7f44714b3e96e14808c9eb98718c7a5d/components/IssueCredentialOptions.yml#L29


> * Trace Credential Issue

https://github.com/w3c-ccg/traceability-interop/blob/1f2adae9ecc366222dc136185c1df78f7cc70bf5/docs/openapi/schemas/IssueCredentialOptions.yml#L14

Both of these are identical with the caveat that we require `'RevocationList2020Status'`


> * VCAPI Credential Status Update

https://github.com/w3c-ccg/vc-api/blob/d275b08a7f44714b3e96e14808c9eb98718c7a5d/issuer.yml#L70

> * Trace Credential Status Update

https://github.com/w3c-ccg/traceability-interop/blob/1f2adae9ecc366222dc136185c1df78f7cc70bf5/docs/openapi/resources/credential-status.yml#L23




Trace & VCAPI  Credential Status update match with both of them utilizing an array with properties:
`type`
`status`

the VCAPI however does not require any of them ( but they don't require any fields in general in their yaml, we already go further and require properties in trace, for example we require the type property to be type `'RevocationList2020Status'`

2022-09-16 21:09 UTC, mkhraisha requested changes
This updates issueCredentialOptions, but does not modify the update credential status endpoint

2022-09-20 17:46 UTC, brownoxford commented
Next steps are to modify the PR to update the other use case for credentialStatus.type and make it required. This is a small enough change to add it to the PR.

2022-09-27 14:12 UTC, brownoxford commented
> This updates issueCredentialOptions, but does not modify the update credential status endpoint

@mkhraisha I believe this was covered in #366?

2022-10-03 19:57 UTC, mkhraisha approved these changes

2022-10-04 17:39 UTC, merged