Adding TraceablePresentation to OAS
w3c-ccg/traceability-interop pull request #407
Opened 2022-09-21 09:59 UTC by nissimsan

Ref: https://github.com/w3c-ccg/traceability-interop/issues/325

2022-09-21 13:11 UTC, OR13 commented on docs/openapi/schemas/VerifiablePresentation.yml
> +      'TraceablePresentation'
This schema should not be a "Traceable Presentation" it should match normative requirements of the W3C TR.

2022-09-21 13:11 UTC, OR13 requested changes
Do not change the example of a normal verifiable presentation.

2022-09-27 12:51 UTC, brownoxford requested changes

2022-09-27 12:51 UTC, brownoxford commented on docs/openapi/schemas/Workflow.yml
> +  }
```suggestion
  {
    "@context": ["https://w3id.org/traceability/v1"],
    "type": ["Workflow"],
    "workflow":
      {
        "instance": ["urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"],
        "definition": ["urn:uuid:n1552885-cc91-4bb3-91f1-5466a0be084e"],
      },
  }
```

Simple whitespace and quote consistency change request

2022-09-27 12:51 UTC, brownoxford commented on docs/openapi/schemas/VerifiablePresentation.yml
> +    'type': ['VerifiablePresentation'],
```suggestion
    "type": ["VerifiablePresentation"],
```

2022-09-27 12:51 UTC, brownoxford commented on docs/openapi/schemas/VerifiablePresentation.yml
> +    '@context': ['https://www.w3.org/2018/credentials/v1'],
```suggestion
    "@context": ["https://www.w3.org/2018/credentials/v1"],
```

2022-09-27 12:51 UTC, brownoxford commented on docs/openapi/schemas/TraceablePresentation.yml
> +    ],
```suggestion
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
```

2022-09-27 12:51 UTC, brownoxford commented on docs/openapi/schemas/TraceablePresentation.yml
> +    ],
```suggestion
    "type': [
      "VerifiablePresentation",
      "TraceablePresentation"
    ],
```

2022-09-27 17:42 UTC, OR13 approved these changes

2022-09-27 17:43 UTC, nissimsan commented
I'll fix the failure for next time.

2022-09-28 15:48 UTC, brownoxford requested changes

2022-09-28 15:48 UTC, brownoxford commented on docs/openapi/schemas/TraceablePresentation.yml
> +    "type': [
```suggestion
    "type": [
```

2022-09-29 10:12 UTC, nissimsan commented
No worries, @brownoxford. The quote helped. :)

2022-09-29 18:10 UTC, brownoxford approved these changes

2022-10-03 19:58 UTC, mkhraisha approved these changes

2022-10-04 17:43 UTC, merged