chore: differentiate between 400 errors
w3c-ccg/traceability-interop pull request #414
Opened 2022-09-22 18:20 UTC by brownoxford

This PR introduces two new specific error responses for use when the request body is not conformant to the expected schema, and for when the request body contains an invalid signature.

Fixes #406

2022-09-23 09:07 UTC, nissimsan approved these changes

2022-09-27 18:21 UTC, OR13 approved these changes

2022-09-27 18:22 UTC, brownoxford commented
This should actually return a 2xx with a failed verification response, this is not a client error

2022-09-27 18:22 UTC, nissimsan commented
@brownoxford , pls add note from the call

2022-09-27 18:23 UTC, OR13 requested changes
invalid signature is a 200 status response... 400 is reserved for malformed questions.

2022-10-04 14:08 UTC, brownoxford commented
Closing in favor of #431

2022-10-04 14:08 UTC, closed without merging