fix: correct linter errors in openapi spec
w3c-ccg/traceability-interop pull request #419
Opened 2022-09-22 21:19 UTC by brownoxford

This PR fixes several linter errors in the OpenAPI specification.

2022-09-27 18:24 UTC, nissimsan requested changes

2022-09-27 18:24 UTC, OR13 approved these changes

2022-09-27 18:25 UTC, nissimsan commented
Pls merge when conflict is resolved, @brownoxford

2022-09-28 18:45 UTC, nissimsan approved these changes

2022-09-28 20:18 UTC, merged