Updating authentication section
w3c-ccg/traceability-interop pull request #451
Opened 2022-10-19 11:42 UTC by nissimsan

Updating based on community feedback: https://github.com/w3c-ccg/traceability-interop/issues/401

2022-10-19 16:26 UTC, TallTed requested changes

2022-10-19 16:26 UTC, TallTed commented on docs/spec/sections/authorization.html
> +        <a href="https://w3c-ccg.github.io/vp-request-spec/#did-authentication">DID Authentication</a>, where the holder
```suggestion
        <a href="https://w3c-ccg.github.io/vp-request-spec/#did-authentication">DID Authentication</a>,
        sometimes referred to as DIDAuth, where the holder 
```

2022-10-19 16:26 UTC, TallTed commented on docs/spec/sections/authorization.html
> +        a Verifiable Presentation, which is
```suggestion
        the verifier, and <a href="https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations/prove">signs</a> 
        a Verifiable Presentation based on that challenge, which is then
```

2022-10-25 17:46 UTC, BenjaminMoe approved these changes

2022-10-25 17:47 UTC, merged