sync README with vocab
w3c-ccg/traceability-interop pull request #478
Opened 2022-12-09 21:36 UTC by TallTed

2022-12-12 17:54 UTC, brownoxford requested changes

2022-12-12 17:54 UTC, brownoxford commented on README.md
> +succesffuly imported the spec:
```suggestion
successfully imported the spec:
```

2022-12-12 20:45 UTC, TallTed commented on README.md
> +succesffuly imported the spec:
Good catch! (How did I miss it?)

2022-12-12 21:05 UTC, brownoxford approved these changes

2022-12-13 08:16 UTC, nissimsan approved these changes

2022-12-13 17:34 UTC, mkhraisha approved these changes

2022-12-13 18:35 UTC, merged