Add documentation for oauth presentation
w3c-ccg/traceability-interop pull request #515
Opened 2023-02-09 20:27 UTC by BenjaminMoe

Addresses: https://github.com/w3c-ccg/traceability-interop/issues/307

2023-02-09 22:01 UTC, TallTed requested changes
Minor tweaks

2023-02-10 13:25 UTC, mprorock approved these changes

2023-02-10 13:27 UTC, mkhraisha approved these changes

2023-02-10 13:33 UTC, nissimsan requested changes

2023-02-10 13:33 UTC, nissimsan commented on docs/tutorials/presentations-exchange-oauth/README.md
> +   - `base_url`: The base URL for the Traceability Interop API.
@BenjaminMoe , this doesn't seem right. It's API_BASE_URL.
The others are also all UPPER_CASE

2023-02-10 13:45 UTC, nissimsan approved these changes

2023-02-10 15:05 UTC, brownoxford approved these changes

2023-02-10 15:56 UTC, merged