Test optional `credentials.id` for `/credentials/issue` requests.
w3c-ccg/traceability-interop pull request #523
Opened 2023-03-07 17:07 UTC by brownoxford

This PR removes the optional `credential.id` from the minimal request body used for testing `/credentials/issue`, and adds a new positive test to ensure that the endpoint works if `credential.id` is included in the request body.

Tests for `/credentials/verify` have not been changed, as verifiable credentials must have an ID.

Fixes #521

2023-03-07 17:55 UTC, mkhraisha approved these changes

2023-03-07 18:37 UTC, OR13 requested changes
This PR will break on GS1 VCs

2023-03-07 18:41 UTC, OR13 commented on tests/conformance_suite.postman_collection.json
> +											" pm.expect(context).to.contain(\"https://w3id.org/traceability/v1\");",
Let us link to an issue to resolve this problem and I will approve.

2023-03-07 18:41 UTC, brownoxford commented
Discussed on call - will create a new issue to track removal of this legacy part of the tests that reference required context content.

2023-03-07 18:42 UTC, OR13 commented on tests/conformance_suite.postman_collection.json
> +											" pm.expect(id).to.equal(pm.variables.get(\"id\"))",
IMO this is the only test that should be present for this case... it is a mistake to repeat tests everywhere.

2023-03-07 19:58 UTC, brownoxford commented on tests/conformance_suite.postman_collection.json
> +											" pm.expect(context).to.contain(\"https://w3id.org/traceability/v1\");",
@OR13 I've removed the legacy test from this new portion of the suite, and created #526 to track removal of the remaining instances of this.

2023-03-14 14:03 UTC, OR13 approved these changes

2023-03-14 15:28 UTC, mkhraisha approved these changes

2023-03-14 17:55 UTC, merged