Feat/verification result update
w3c-ccg/traceability-interop pull request #535
Opened 2023-03-10 20:46 UTC by rhofvendahl

This PR addresses issue https://github.com/w3c-ccg/traceability-interop/issues/481.

2023-03-10 21:36 UTC, brownoxford commented
I would remove `verifications` entirely from the example.

2023-03-10 21:37 UTC, brownoxford requested changes
have to add a comment to request changes :(

2023-03-11 02:02 UTC, rhofvendahl commented
@brownoxford just did

2023-03-14 15:29 UTC, mkhraisha approved these changes

2023-03-14 17:59 UTC, BenjaminMoe approved these changes

2023-03-14 17:59 UTC, merged