feat: change vc-format header to content-type
w3c-ccg/traceability-interop pull request #573
Opened 2023-07-09 03:54 UTC by rhofvendahl

2023-07-10 13:51 UTC, brownoxford approved these changes

2023-07-10 14:24 UTC, brownoxford requested changes
Actually, do we need to update the `enum` for `content-type`?

We may also want to create separate issues for:
* Updating relevant unit tests to include this header in requests
* Add negative unit testing for incorrect/missing values
* Update respec document with normative language describing the use of this header

2023-07-10 21:51 UTC, rhofvendahl commented
@brownoxford What would you suggest we update it to? On reflection it might be good to include `vc-cwt`, is that what you mean?

2023-07-10 21:56 UTC, OR13 commented
See this thread on the accept header

https://github.com/vcstuff/draft-terbu-sd-jwt-vc/pull/118#issuecomment-1629782037

2023-07-10 21:58 UTC, OR13 commented
POST /credentials/issue

Body = claimset (with the server reserving the right to override things)

--accept vc+ld+jwt

2023-07-11 17:47 UTC, OR13 commented on docs/openapi/parameters/header/contentType.yml
> +name: content-type
change to the accept header.... use `application/vc+ld+jwt` and `application/vc+ld+json` for the enum

2023-07-11 17:47 UTC, OR13 requested changes
see comments

2023-07-11 17:48 UTC, nissimsan commented
@rhofvendahl, pls consider comments.

2023-07-18 13:59 UTC, brownoxford commented on docs/openapi/parameters/header/contentType.yml
> +name: content-type
```suggestion
name: accept
```

2023-07-18 17:43 UTC, OR13 approved these changes

2023-07-18 17:43 UTC, merged