chore: add test for duplicate issuer value
w3c-ccg/traceability-interop pull request #597
Opened 2023-10-03 15:42 UTC by brownoxford

This PR adds a negative conformance test for duplicate JSON key `issuer` in a credentials issue request. The expectation is that the issuer will return a 400 error response.

This test is added into a new sub-folder called "Duplicate Keys" because any tests like this will differ from our standard tests in that it is not a simple mutation of the minimal request JSON object (you can't add duplicate keys in JSON). If we add more tests here,  each one will have a request body in raw text (not JSON) that includes the minimal credentials issue request with the appropriate key duplicated.

When we discuss this on call, we should determine whether or not we feel we need duplicate key tests for all keys.

Fixes #539

2023-10-03 17:44 UTC, nissimsan approved these changes

2023-10-10 17:38 UTC, BenjaminMoe approved these changes

2023-10-10 17:41 UTC, brownoxford commented
This should be modified to EITHER return 400 OR make sure that the last provided value for the duplicate key is the one that is used in the returned credential.

2023-10-10 17:42 UTC, mkhraisha requested changes
Would love it if this accommodate the standard JSON behavior to use the latest duplicate value rather than to error out.

2023-10-17 16:13 UTC, mkhraisha approved these changes

2023-10-17 17:38 UTC, merged