changes to abstract
w3c-ccg/traceability-interop pull request #620
Opened 2024-01-16 18:00 UTC by mkhraisha

closes #528 

Got kind of stuck writing this, would love any improvements or suggestions.

2024-01-16 18:13 UTC, brownoxford commented
Looks like we just need bullet point 4, `references VC API should be moved to its own section "Relationship to VC-API"`

2024-01-16 18:14 UTC, mkhraisha commented
That is tackled in issue #529

2024-01-16 18:15 UTC, mkhraisha commented
The comment in this issue is about removing it

2024-01-16 18:56 UTC, TallTed requested changes
Minor

2024-01-16 18:56 UTC, TallTed commented on docs/spec/sections/abstract.html
> +    This specification utilizes the [Decentralized Identifiers (DIDs) v1.0](https://www.w3.org/TR/did-core/)
```suggestion
    This specification uses the [Decentralized Identifiers (DIDs) v1.0](https://www.w3.org/TR/did-core/)
```

2024-01-23 18:47 UTC, nissimsan approved these changes

2024-01-23 18:47 UTC, brownoxford approved these changes

2024-01-23 18:50 UTC, merged