Attempt to remove transmute from repo
w3c-ccg/traceability-interop pull request #623
Opened 2024-02-08 18:08 UTC by acarnagey

An attempt to remove Transmute from interop and conformance tests

2024-02-09 15:36 UTC, BenjaminMoe approved these changes

2024-02-12 08:43 UTC, nissimsan approved these changes

2024-02-14 22:18 UTC, OR13 approved these changes
please merge this

2024-02-15 18:42 UTC, brownoxford approved these changes

2024-02-15 18:47 UTC, mkhraisha requested changes

2024-02-15 18:47 UTC, mkhraisha commented on environment-setup/README.md
> -          - name: "mesur.io-Transmute"
Can you use any of the other existing ones rather than example? 
Something like mavennet or gs1

2024-02-15 18:58 UTC, mkhraisha approved these changes

2024-02-15 18:58 UTC, merged