Update mandatory-to-implement-algorithms
w3c-ccg/traceability-interop pull request #626
Opened 2024-03-06 19:43 UTC by OR13

2024-03-08 12:31 UTC, nissimsan commented
I included the same on https://github.com/w3c-ccg/traceability-interop/pull/628 too, let's close this to avoid conflict.

2024-03-08 12:31 UTC, nissimsan requested changes
[Dupe](https://github.com/w3c-ccg/traceability-interop/pull/628), let's just close this

2024-03-20 08:36 UTC, nissimsan approved these changes

2024-03-20 15:03 UTC, brownoxford approved these changes

2024-03-20 23:36 UTC, brentzundel approved these changes

2024-03-21 10:33 UTC, nissimsan commented
Pls ignore my earlier comments.

2024-04-02 18:14 UTC, mkhraisha approved these changes

2024-04-02 18:14 UTC, merged