Consistent trace vocab reference
w3c-ccg/traceability-interop pull request #633
Opened 2024-03-20 08:34 UTC by nissimsan

2024-03-20 15:00 UTC, brownoxford approved these changes

2024-03-20 16:50 UTC, mkhraisha approved these changes

2024-03-20 17:06 UTC, TallTed requested changes
ReSpec magic

2024-03-20 17:06 UTC, TallTed commented on docs/spec/index.html
> +          the [[[TRACE-VOCAB]]].
```suggestion
          the [[[TRACE-VOCAB]]] [[TRACE-VOCAB]].
```

2024-03-20 17:06 UTC, TallTed commented on docs/spec/index.html
>        document. This specification does not define any additional terms.
```suggestion
      [[[TRACE-VOCAB]]] [[TRACE-VOCAB]].
      This specification does not define any additional terms.
```

2024-03-20 17:06 UTC, TallTed commented on docs/spec/sections/abstract.html
> +    Specification [[TRACE-VOCAB]].
```suggestion
    Exchanged Verifiable Credentials often implement schemas defined in
    the [[[TRACE-VOCAB]]] [[TRACE-VOCAB]]..
```

2024-03-20 23:34 UTC, brentzundel approved these changes

2024-04-02 18:11 UTC, mkhraisha commented
Please fix the change to the vc data model reference previously merged in and merge out of band

2024-04-02 18:44 UTC, nissimsan commented
Fixed the overwrite from merge conflict. Merging.

2024-04-02 18:44 UTC, merged