fix: presentation authentication section
w3c-ccg/traceability-interop pull request #652
Opened 2024-04-22 13:04 UTC by nissimsan

This still had reminiscences of supporting multiple ways to authenticate. This should make it more readable. 

Title updated to Authentication, which is what the section is actually about. (Note that I have not updated references and file name to avoid merge collisions - to be updated in a later PR). 

Closes #644.

2024-04-22 14:50 UTC, OR13 commented on docs/spec/sections/authorization.html
> +      At time of presentation, the holder MUST authenticates by obtaining an
```suggestion
      At time of presentation, the holder MUST authenticate by obtaining an
```

2024-04-22 17:43 UTC, TallTed requested changes
Rereading always reveals something else to fix...

2024-04-22 17:43 UTC, TallTed commented on docs/spec/sections/authorization.html
> +      The following sequence of events are required in order for a holder to present data to a verifier:
```suggestion
      The following sequence of events is necessary for a holder to present data to a verifier:
```

2024-04-22 17:43 UTC, TallTed commented on docs/spec/sections/authorization.html
>          providing client id and secret to the holder.
```suggestion
        providing client ID and secret to the holder.
```

2024-04-25 15:26 UTC, mkhraisha approved these changes

2024-04-25 19:08 UTC, brentzundel approved these changes

2024-04-25 19:09 UTC, merged