cleanup spec text, update links, example, and references
w3c-ccg/traceability-interop pull request #672
Opened 2024-09-12 17:24 UTC by mkhraisha

Did a review of the document, cleaned up text, links, examples and references

2024-09-12 18:12 UTC, TallTed requested changes
Editorial language fixes

2024-09-12 18:12 UTC, TallTed commented on docs/spec/index.html
>        the project, please reference the
```suggestion
      the project, please refer to the
```

2024-09-12 18:12 UTC, TallTed commented on docs/spec/index.html
> +            asynchronous nature of this mode of data exchange, that they
```suggestion
            asynchronous nature of this mode of data exchange, in that they
```

2024-09-12 18:12 UTC, TallTed commented on docs/spec/index.html
> +            present an area where various attacks could arise by sending
```suggestion
            present an area where various attacks could send
```

2024-09-12 18:12 UTC, TallTed commented on docs/spec/index.html
> +            Identifiers conformant with this spec <em>MUST</em> be
```suggestion
            Identifiers conformant with this specification <em>MUST</em> be
```

2024-09-12 18:45 UTC, TallTed commented on docs/spec/index.html
> +            present an area where various attacks could arise by sending
or
```suggestion
            present an area where various attacks could be made by sending
```

2024-09-19 19:06 UTC, nissimsan approved these changes

2024-09-19 19:08 UTC, merged