Revise workflow terms
w3c-ccg/traceability-interop pull request #72
Opened 2022-01-31 20:04 UTC by OR13

aligns with: https://github.com/w3c-ccg/traceability-interop/pull/70

2022-01-31 20:31 UTC, OR13 commented on docs/index.html
> +                "correlationId": "d2dfc100-9384-49e4-b547-5e7d84ec5bf5"
goal here to make it clear this is an identifier used to group things... and describe the cases for grouping in the following sections.

- groups of definitions
- groups of instances
- groups of nodes in a path

2022-01-31 21:01 UTC, TallTed commented on docs/index.html
> +            We acknowledge that different use cases, may have complicated workflows, which may yield
```suggestion
            In the context of this API profile, we consider the specifics of workflows out of scope.
            We acknowledge that different use cases may have complicated workflows, which may yield 
```

2022-01-31 21:03 UTC, TallTed commented on docs/index.html
> +            in advance by a user or system, or a root path that has already occurred
```suggestion
            in advance by a user or system, or is a root path that has already occurred
```

2022-01-31 21:04 UTC, TallTed commented on docs/index.html
> +             Meaning that PATHs represent partial information related to a workflow instance.
```suggestion
             of all "Workflow Instance" related credentials. In other words,
             PATHs represent partial information related to a workflow instance.
```

2022-02-01 04:52 UTC, mprorock reviewed
I like the examples here - I think we need to keep the concept of "paths" though as a general term - highly useful and clarifies the graph like structure of the data we are dealing with.

2022-02-01 14:47 UTC, OR13 commented
@mprorock I agree.. I think path is needed to explain that not all parties will see the "full graph" but that some parties may require a partial view of that graph that aligns with a particular path.

2022-02-01 19:20 UTC, mprorock requested changes
let's keep path, and add a very specific definition for WORKFLOW

2022-02-01 19:20 UTC, mprorock commented on docs/index.html
> -        </dd>
let's keep this, and add a definition for WORKFLOW

2022-02-01 20:31 UTC, mkhraisha approved these changes
on further review this lgtm

2022-02-03 13:42 UTC, mprorock commented on docs/index.html
> -        </dd>
perfect - i am dumb and misread.

2022-02-03 13:42 UTC, mprorock approved these changes

2022-02-03 13:42 UTC, merged